#!/usr/bin/with-contenv sh

# Create configuration files from templates
if [ -f /opt/alice-gkeep-dialogs/config.yml.j2 ];then
    j2 --filter /opt/j2cli/env_json.py -o /opt/alice-gkeep-dialogs/config.yml /opt/alice-gkeep-dialogs/config.yml.j2
    rm /opt/alice-gkeep-dialogs/config.yml.j2
fi
